language: node_js
sudo: required
services:
- docker
node_js:
- '5'
before_script:
- npm install
script:
- ./node_modules/bower/bin/bower install jquery bootstrap
- ./node_modules/nar/bin/nar create
- docker build -t therickys93/barorderstatus
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; docker push therickys93/barorderstatus
  fi
- sh set_tags.sh
deploy:
  provider: releases
  api_key:
    secure: YT6/G3ME6d2yGAZBw9ZmYPNzzWePKHDwEZeBzJDsavJ69qMWxA0v69P4rpDcGWbMdJl3+co2QgPfu8OcelztXADyUIeu6LgQ1ZlNEPRarxSSBfHkjiifpc20AaBH8NPfaCW5DFigDOzdM1t4UxjqDdYkgiWteVXyvI7V/DmV6C+Y8gc2+m8zjFQ0GHsxfhOe6Aiw59u4lCdV2NUQRU7iQpIUaHf6HewDJV4vinAN9U88qTF+mAP+1mZCNXffYX7BeGuHMVoBxISQ8ULY9FpgwLuoVQq7zp8USTXyAdNw5OxowxYwKeq1CCEi/hLBoKvnx2z6i/BJPzHenitP57SLK4p4cOsGXbRkz5XF8WwpHGdtPtiQpqvwLTD+++/l7KAgAnpbUO3Ykyt51MWm/zrtRv2FiztbV6Xc4h+u4zU/Kk5qLPegHhfag4HZ56maQaWjP6GZWLOccLnEp54rmlBTdZfkQf+DySSFC4bJGZNlc4NEYMTl4bNFK2gg1fei5eTFSLvi2iSFc6z6IuBZUlotP6PPynV8DC5o0VqcIda+e6etK+gbOapguYqDaPVsgwSjqWkbuEuDD/tks9Ahz1Me3eIR6AgdKSkvNWY1ry2uGPGh60557m/ur4050/bQKcAqHDLVoM7FBi0+MvmbxQuz/kuW234vYZcWh1Z2I1+D47A=
  file: status-*.nar
  file_glob: "true"
  skip_cleanup: true
  on:
    branch: master
    repo: therickys93/barorderstatus
